spring.application.name=uniride
server.port=8080

# MySQL (Railway)
spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:38340/railway
spring.datasource.username=root
spring.datasource.password=hvbCAIKoJUbfqnkrehluBbYhDxdWzKMQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Google Maps API Key (replace with yours)
google.maps.api-key=AIzaSyCyXRZqkNufKDXeGazX_AL35I9Jl2UDIAk

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Logging
logging.level.com.project.uniride=DEBUG
