spring.application.name=uniride
server.port=8080

# MongoDB
 spring.data.mongodb.uri=mongodb+srv://jackjdugan_db_user:hYlfAid39vxEs0Pf@cluster0.h1tlme7.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=uniride

# Google Maps API Key (replace with yours)
google.maps.api-key=AIzaSyCyXRZqkNufKDXeGazX_AL35I9Jl2UDIAk

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=UniRideBeta.noreply@gmail.com
spring.mail.password=ablakvyqgyzctlqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging
logging.level.com.project.uniride=DEBUG
